name: deploy

on:
  workflow_dispatch: {}

jobs:

  pypi:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Package
        env:
          PIP_INDEX_URL: 'https://:2023-04-16T23:56:46Z@time-machines-pypi.sealsecurity.io/'
          PIP_CONSTRAINT: ${{ github.workspace }}/../hatchling-constraint.txt
        run: |
          echo "hatchling==1.14.0" > "${{ github.workspace }}/../hatchling-constraint.txt"
          pip install --upgrade build
          python -m build -s -w
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
          if-no-files-found: error
